# Generated by Django 5.2 on 2026-05-07 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_blog_author_alter_blog_id_alter_blog_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2026, 5, 7, 18, 22, 4, 140377),
                verbose_name="Опубликована",
            ),
        ),
    ]
