# Generated by Django 5.2 on 2026-05-07 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_blog_posted_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "verbose_name": "статья блога",
                "verbose_name_plural": "статьи блога",
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.FileField(
                default="temp.jpg", upload_to="", verbose_name="Путь к картинке"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2026, 5, 7, 18, 40, 32, 152294),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2026, 5, 7, 18, 40, 32, 152294),
                verbose_name="Дата добавления",
            ),
        ),
    ]
